Fix trait not found
webstacknl/api-platform-extensions-bundle pull request #14
Opened 2023-04-27 12:26 UTC by tienvx

The exception is `Uncaught ReflectionException: Class "ApiPlatform\Util\ClassInfoTrait" not found while loading "Webstack\ApiPlatformExtensionsBundle\EventListener\MeListener"`

This PR create a new trait, which require more code, but still provide support for `api-platform/core:3.0`. Do we just simply require `api-platform/core:^3.1` and use `ApiPlatform\Metadata\Util\ClassInfoTrait` directly?

2023-05-03 13:02 UTC, mwansinck commented
@tienvx Thanks for your PR. Currently we haven't yet used our bundle with Api Platform 3 yet. Your approach seems good to me.

2023-05-03 13:03 UTC, mwansinck approved these changes

2023-06-07 08:29 UTC, rvmourik requested changes
Hi @tienvx 

First of all, sorry for the delay and thank you for contributing. The PR looks good, I have added a minor RFC.

Hope you have the time to change this, so we can merge and tag it.

Thanks

2023-06-07 08:29 UTC, rvmourik commented on src/Util/ClassInfoTrait.php
> +if (trait_exists(MetadataClassInfoTrait::class)) {
Maybe add some comments which tells what trait is used in 2.x and 3.x.

2023-06-07 08:29 UTC, rvmourik requested changes
Hi @tienvx 

First of all, sorry for the delay and thank you for contributing. The PR looks good, I have added a minor RFC.

Hope you have the time to change this, so we can merge and tag it.

Thanks

2026-04-14 20:49 UTC, closed without merging